def raise_exception():
    raise TypeError("This is already defined exception.")
